"use client";

import { useMemo, useState } from "react";
import { JobCandidateStatus } from "@/server/db";

import type { MatchRow } from "./JobMatchesTable";

type Props = {
  jobId: string;
  matches: MatchRow[];
};

type CopyState = "idle" | "success" | "error";
type ExportState = "idle" | "loading" | "success" | "error";

export function ShortlistActions({ jobId, matches }: Props) {
  const shortlisted = useMemo(
    () =>
      matches
        .filter((match) => match.shortlisted ?? match.jobCandidateStatus === JobCandidateStatus.SHORTLISTED)
        .map((match) => ({
          ...match,
          confidenceBand: match.confidenceCategory ?? null,
        })),
    [matches],
  );
  const [copyState, setCopyState] = useState<CopyState>("idle");
  const [exportState, setExportState] = useState<ExportState>("idle");

  const escapeCsv = (value: unknown) => `"${String(value ?? "").replace(/"/g, '""').replace(/\r?\n/g, " ")}"`;

  function formatPercent(value?: number | null) {
    if (typeof value !== "number") return "—";
    return `${Math.round(value)}%`;
  }

  function deriveStrengths(match: MatchRow): string[] {
    const explanation = match.explanation as { topReasons?: string[] } | undefined;
    const reasons = explanation?.topReasons ?? [];
    const skills = match.keySkills ?? [];
    const combined = [...reasons, ...skills.map((skill) => `${skill} coverage`)];

    while (combined.length < 3) {
      combined.push("Relevant strengths recorded by the matcher.");
    }

    return combined.slice(0, 3);
  }

  function deriveRisks(match: MatchRow): string[] {
    const explanation = match.explanation as { riskAreas?: string[] } | undefined;
    const risks = explanation?.riskAreas ?? [];

    if (risks.length === 0) {
      return ["No critical risks recorded", "Confirm details during outreach"];
    }

    const padded = [...risks];
    while (padded.length < 2) {
      padded.push("Confirm role expectations in follow-up.");
    }

    return padded.slice(0, 2);
  }

  async function handleDownloadCsv() {
    setExportState("loading");

    if (shortlisted.length === 0) {
      setExportState("error");
      return;
    }

    const headers = [
      "Candidate",
      "Score",
      "Confidence",
      "Top strength 1",
      "Top strength 2",
      "Top strength 3",
      "Risk 1",
      "Risk 2",
    ];

    const rows = shortlisted.map((match) => {
      const strengths = deriveStrengths(match);
      const risks = deriveRisks(match);

      return [
        match.candidateName ?? "Name not provided",
        formatPercent(match.score),
        match.confidenceCategory ?? "—",
        strengths[0],
        strengths[1],
        strengths[2],
        risks[0],
        risks[1],
      ];
    });

    const csvLines = [headers.map(escapeCsv).join(","), ...rows.map((row) => row.map(escapeCsv).join(","))];
    const blob = new Blob([csvLines.join("\r\n")], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `shortlist_${jobId}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setExportState("success");
  }

  async function handleCopyShortlist() {
    setCopyState("idle");

    if (shortlisted.length === 0) {
      setCopyState("error");
      return;
    }

    if (!navigator?.clipboard?.writeText) {
      setCopyState("error");
      return;
    }

    const headers = ["Candidate", "Email", "Title", "Match", "Confidence", "Notes"];
    const rows = shortlisted.map((match) => [
      match.candidateName ?? "Name not provided",
      match.candidateEmail ?? "—",
      match.currentTitle ?? "—",
      formatPercent(match.score),
      formatPercent(match.confidenceScore),
      match.jobCandidateNotes ?? "",
    ]);

    const lines: string[] = [];
    lines.push(`Shortlist for Job ${jobId}`);
    lines.push("");
    lines.push(`| ${headers.join(" | ")} |`);
    lines.push(`| ${headers.map(() => "---").join(" | ")} |`);
    for (const row of rows) {
      lines.push(`| ${row.join(" | ")} |`);
    }
    lines.push("");
    lines.push("_Generated by EDGE Talent Engine shortlist export._");

    try {
      await navigator.clipboard.writeText(lines.join("\n"));
      setCopyState("success");
    } catch (error) {
      console.error("Failed to copy shortlist", error);
      setCopyState("error");
    }
  }

  return (
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <div className="text-sm text-gray-700">
        Shortlisted candidates: <span className="font-semibold">{shortlisted.length}</span>
      </div>
      <div className="flex flex-wrap gap-3">
        <button
          type="button"
          onClick={handleCopyShortlist}
          disabled={shortlisted.length === 0}
          className="inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-900 shadow-sm transition hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-60"
        >
          {copyState === "success" ? "Copied" : "Copy shortlist to clipboard"}
        </button>
        <button
          type="button"
          onClick={handleDownloadCsv}
          disabled={shortlisted.length === 0 || exportState === "loading"}
          className="inline-flex items-center rounded-md bg-blue-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 disabled:cursor-not-allowed disabled:bg-blue-300"
        >
          {exportState === "loading" ? "Preparing…" : "Download shortlist CSV"}
        </button>
      </div>
    </div>
  );
}
