"use client";

import { useMemo, useState } from "react";
import { JobCandidateStatus } from "@prisma/client";

import type { MatchRow } from "./JobMatchesTable";

type Props = {
  jobId: string;
  matches: MatchRow[];
};

type CopyState = "idle" | "success" | "error";
type ExportState = "idle" | "loading" | "success" | "error";

export function ShortlistActions({ jobId, matches }: Props) {
  const shortlisted = useMemo(
    () => matches.filter((match) => match.jobCandidateStatus === JobCandidateStatus.SHORTLISTED),
    [matches],
  );
  const [copyState, setCopyState] = useState<CopyState>("idle");
  const [exportState, setExportState] = useState<ExportState>("idle");

  async function handleExportShortlist() {
    setExportState("loading");

    if (shortlisted.length === 0) {
      setExportState("error");
      return;
    }

    try {
      const response = await fetch(`/api/agents/shortlist/export?jobReqId=${encodeURIComponent(jobId)}`);

      if (!response.ok) {
        throw new Error("Export failed");
      }

      const blob = await response.blob();
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `shortlist_${jobId}.csv`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      setExportState("success");
    } catch (error) {
      console.error("Failed to export shortlist", error);
      setExportState("error");
    }
  }

  function formatPercent(value?: number | null) {
    if (typeof value !== "number") return "—";
    return `${Math.round(value)}%`;
  }

  async function handleCopyShortlist() {
    setCopyState("idle");

    if (shortlisted.length === 0) {
      setCopyState("error");
      return;
    }

    if (!navigator?.clipboard?.writeText) {
      setCopyState("error");
      return;
    }

    const headers = ["Candidate", "Email", "Title", "Match", "Confidence", "Notes"];
    const rows = shortlisted.map((match) => [
      match.candidateName ?? "Name not provided",
      match.candidateEmail ?? "—",
      match.currentTitle ?? "—",
      formatPercent(match.score),
      formatPercent(match.confidenceScore),
      match.jobCandidateNotes ?? "",
    ]);

    const lines: string[] = [];
    lines.push(`Shortlist for Job ${jobId}`);
    lines.push("");
    lines.push(`| ${headers.join(" | ")} |`);
    lines.push(`| ${headers.map(() => "---").join(" | ")} |`);
    for (const row of rows) {
      lines.push(`| ${row.join(" | ")} |`);
    }
    lines.push("");
    lines.push("_Generated by EDGE Talent Engine shortlist export._");

    try {
      await navigator.clipboard.writeText(lines.join("\n"));
      setCopyState("success");
    } catch (error) {
      console.error("Failed to copy shortlist", error);
      setCopyState("error");
    }
  }

  return (
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <div className="text-sm text-gray-700">
        Shortlisted candidates: <span className="font-semibold">{shortlisted.length}</span>
      </div>
      <div className="flex flex-wrap gap-3">
        <button
          type="button"
          onClick={handleCopyShortlist}
          disabled={shortlisted.length === 0}
          className="inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-semibold text-gray-900 shadow-sm transition hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-60"
        >
          {copyState === "success" ? "Copied" : "Copy shortlist to clipboard"}
        </button>
        <button
          type="button"
          onClick={handleExportShortlist}
          disabled={shortlisted.length === 0 || exportState === "loading"}
          className="inline-flex items-center rounded-md bg-blue-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-blue-700 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-600 disabled:cursor-not-allowed disabled:bg-blue-300"
        >
          {exportState === "loading" ? "Exporting…" : "Export shortlist"}
        </button>
      </div>
    </div>
  );
}
