/**
 * @vitest-environment jsdom
 */

import "@testing-library/jest-dom/vitest";
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { vi, describe, beforeEach, it, expect } from "vitest";

import { TS_CONFIG } from "@/config/ts";
import { JobMatchesView } from "@/components/JobMatchesView";

const refresh = vi.fn();

vi.mock("next/navigation", () => ({
  useRouter: () => ({
    refresh,
  }),
}));

const shortlistedRow = {
  candidateId: "cand-1",
  candidateName: "Jordan Steele",
  candidateTitle: "Data Scientist",
  matchScore: 92,
  confidence: 88,
  explanationSummary: "Top match across skills and recency",
  confidenceDetails: null,
  confidenceReasons: null,
  shortlisted: true,
};

describe("JobMatchesView shortlist flows", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.stubGlobal("fetch", vi.fn());
    Object.defineProperty(navigator, "clipboard", {
      value: { writeText: vi.fn().mockResolvedValue(undefined) },
      configurable: true,
    });
  });

  it("calls shortlist endpoint and refreshes after persisting", async () => {
    const user = userEvent.setup();
    const response = new Response(JSON.stringify({ ok: true }), { status: 200 });
    (fetch as unknown as vi.Mock).mockResolvedValue(response);

    render(<JobMatchesView jobId="job-123" initialData={[shortlistedRow]} />);

    await user.click(screen.getByRole("button", { name: /run shortlist/i }));

    expect(fetch).toHaveBeenCalledWith(
      "/api/jobs/job-123/shortlist",
      expect.objectContaining({
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          minMatchScore: TS_CONFIG.shortlist.minMatchScore,
          minConfidence: TS_CONFIG.shortlist.minConfidence,
          maxShortlisted: TS_CONFIG.shortlist.topN,
        }),
      }),
    );

    await waitFor(() => expect(refresh).toHaveBeenCalled());
  });

  it("exports shortlisted candidates with CSV headers", async () => {
    const user = userEvent.setup();
    const createObjectURL = vi.fn().mockReturnValue("blob:shortlist");
    const revokeObjectURL = vi.fn();
    const originalURL = globalThis.URL;
    const originalBlob = globalThis.Blob;
    const capturedParts: BlobPart[] = [];

    class MockBlob extends Blob {
      constructor(parts: BlobPart[], options?: BlobPropertyBag) {
        capturedParts.push(...parts);
        super(parts, options);
      }
    }

    // @ts-expect-error - overriding for test environment
    globalThis.URL = { ...(originalURL as object), createObjectURL, revokeObjectURL };
    // @ts-expect-error - overriding for test environment
    globalThis.Blob = MockBlob;

    render(<JobMatchesView jobId="job-456" initialData={[shortlistedRow]} />);

    await user.click(
      screen.getByRole("button", { name: /download shortlist csv/i }),
    );

    const blobArg = createObjectURL.mock.calls[0][0] as Blob;
    expect(blobArg).toBeInstanceOf(MockBlob);
    const csvText = capturedParts.join("");

    expect(csvText).toContain(
      '"Candidate ID","Candidate Name","Title","Match Score","Confidence","Why (Summary)"',
    );
    expect(csvText).toContain(
      '"cand-1","Jordan Steele","Data Scientist","92","88","Top match across skills and recency"',
    );

    // cleanup URL override
    globalThis.URL = originalURL;
    globalThis.Blob = originalBlob;
  });

  it("copies an email-ready shortlist table to the clipboard", async () => {
    const user = userEvent.setup();
    const writeText = vi.fn().mockResolvedValue(undefined);
    Object.defineProperty(navigator, "clipboard", {
      value: { writeText },
      configurable: true,
    });

    render(<JobMatchesView jobId="job-789" initialData={[shortlistedRow]} />);

    await user.click(
      screen.getByRole("button", { name: /copy shortlist to clipboard/i }),
    );

    expect(writeText).toHaveBeenCalledTimes(1);
    const copied = writeText.mock.calls[0][0] as string;

    expect(copied).toContain("Shortlist for Job job-789");
    expect(copied).toContain("| Candidate | Title | Match | Confidence | Why (Summary) |");
    expect(copied).toContain("| Jordan Steele | Data Scientist | 92% | 88% | Top match across skills and recency |");
    expect(copied).toContain("_Generated by ETE-TS shortlist (Match + Confidence based)._");
  });
});
